#----------------------------------------------------------------------
# This file was generated by C:\Python34\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

logo_16 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACdklEQVR42q2T3UtTYRzHf8/Z'
    b'We4lXFdR6k0WcpwNpw4rEDMxi7QFRUJUBOE/0FWURXTRFoW9XIjiZVSYkmW+LQsLmukyTbOt'
    b'xnoRdfam4LSO29H59N3yXDTyqg58+PLwHD7P93mec5iDHPQvD/tvglN0ehpxA5SDdmAH98F+'
    b'0AgOgZugElxwkuNaoqAG0QOsYBhTOcgBIm5DvgBbwXOwHbRC8DBREAiL2jv6dqWUZugRVbDd'
    b'ROs7OE2Wy0QthlgTRWmipKQjZDRedf6sqvtTwKpqI6LWvbZ+yqqbmxkOV6bnrllcNzDKvbYw'
    b'lz36VaZtfGKih2VkFJFe/8A5f9YVF3CiEPL2cnU3KAZdxPkemuRtlCrYSdTeowXlAPn9jSRJ'
    b'R8lgqHbKZ2pVQTWyH7UsnDGfIoibscJrHvTm0LepQa1ky6PUlH7NG+8WHgj0MkkqxHwbGnSp'
    b'go/Iu1ixeInoqUBUEiVyfeplZYIupc0neuyrxenmoszsg4vBYIOYlnYMDS6jQY0quBJvIMtm'
    b'Pi+/ZcpC1tJSeCQ4VWgVhE2vPvhO5hp0P/ptBTvyo+PjfRqrtQANOtDgsSoYVRvQ7OwTMpl2'
    b'YuzCuIw+y62UYtwXnyc6DG6B4+AirvG6KrgUv+9oVOJzc35msZh5cvIIH/Jk05evQ3yjOYfp'
    b'kl4KimLmnA+ySCQf73dD8EwVjCObsGIJJN2k0cQadIK92FYLDrcCletR+a/ffEzgRA7S2JhE'
    b'4bAfokzgxUFZKBQaJoslDx+P2xk517mS4DuyAZSC2MHsWv4XYntvXv4H6lD5/EqCE0gfVtxA'
    b'vw80HbwHGeAdtpEVa6juOfH5BayACOBDTDJSAAAAAElFTkSuQmCC')
index.append('logo_16')
catalog['logo_16'] = logo_16
getlogo_16Data = logo_16.GetData
getlogo_16Image = logo_16.GetImage
getlogo_16Bitmap = logo_16.GetBitmap

#----------------------------------------------------------------------
logo_32 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABdklEQVR42mNsY2hjGEjAOOqA'
    b'QeeASoaq/zB2O0MbI7X5JDkACHyAeAs1+UBHbB3cDoA6whuugIFhK9BFVOOTFAKMIDTzPyJE'
    b'0hkZGf4zIPiMDIz//yPk2xnbGSv/V6LyKU0DjDP/I4KQ/YYPQ7wmnK/IoOh3j+HeJmIdQFQU'
    b'DLgDsKUBhgXX4XyGBM2tiv8VfWHcVMbUzQwEALJ5GA4AOg9nvmVEkwfzkeKcEQgw9JOaBpAN'
    b'YCAmW/1HRAm6A9DliYqCAXcAiCA1X6MHI758DgJEpwGscYzGf3RRFs6X03/MuHDhQjg/Pj4e'
    b's1wgOQ2gBzEeB/z5x+F7+FINPBcoiooG23p6rqUsDdDbAdjSAAMBcO+8qg+MrWR4e8uhbduC'
    b'YPwjXhfWUTcNkCqPp1whLw2QKk9qdTzgDgARpORzYsoB9DinajlAqC5gIBGQnA3xOQBbEA9+'
    b'B4AIUssBdECoLiA6BBgp5FMnDVC52T34HQAiaNnuJwQAEOa8sD+VtYwAAAAASUVORK5CYII=')
index.append('logo_32')
catalog['logo_32'] = logo_32
getlogo_32Data = logo_32.GetData
getlogo_32Image = logo_32.GetImage
getlogo_32Bitmap = logo_32.GetBitmap

#----------------------------------------------------------------------
logo_48 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAGHklEQVR42u2Za1AWZRTHz8Yk'
    b'9SVBAeEltKLpNjVTn/zgR2nG7Gppl5lKaxi6i70J6FtiyQglpGlaWdPNmqnwkl3GgBRQIs2x'
    b'Gw1jWomlZSKVtyD50PY/8+yrZ3fPFmv71jDDzvxZ5j9nluf37O5/z/NgVVM1DebDGgIYAhgC'
    b'0AFmU8JW7FHQfsXPhX5W/Dxon+LHoJ8UPx/6UfELaqh6bxQAU6FXFf9O6CXFL4GeV/x7oGcV'
    b'fzq0RPFnAeCJKAAehBYpfhlUq16GqEbx50BVij8PqlT8RQCIRwFQCi1W/IegJxW/AtJm7mFo'
    b'vuI/6sh71AGgLAqAB6CnFT+qO8OzP0/xFwCgIiwAn26Hhgt7I5mX7AooU/ht0A+OP0L47VCX'
    b'448U/sfQd9AEKFv4n0A7HD9H+J8BoD2KO5BlLbd7FD+bSqwDip9jk30Y59HQacLnxDoEjfH4'
    b'+8mytJTLA4CWcqEBbgPAaz63j6ZRqfWKUl8MgGYy7815wl8INTnni4S/BADLlOuUA0B7FMOn'
    b'EAD8z3ofnvVSS/sDuIi9Fue1HgB+1uuhNR6AKgDMUa4TWQpNB4A/p/soDoCF2swB4D2cV0IX'
    b'SzBoNfQWdKnw5wLgMeU6kaXQyQLwbF+iALwJXTYAgFoAlIcF4BN/YWUKtVhr7L0Y8FUkU6gX'
    b'6VRsfY/friR32rQBgNOG67OE/xH0jVMv02YzAL7GeSKZtiV5bANAmwqAaVbTBtLShgf3i1pv'
    b'20dxLoDShc+poqVTNuoPO/UyhbpR363U5wJAS6dAgFugNxT/Vuh1xZ+KAXFO8wteKPw6DEjv'
    b'kWybU4i/3hcKfynqn1HqZwJA+9IHAoT/4tp2A5m0kQAJDEh7RitRH00KBQDcC2kzEdQtxp0Z'
    b'XemZ0XIMaIFSn0B9NCkUMUC9Z0b/CeDfpxD/AMFdOJ3heAy0nsyC41ooQ9RvINPzsC97nhYM'
    b'qMvxZQq1YkCcQteQu+fZhPqdOF9N7rRpR/12MqmVK/ytANgY5g5k4g/04XwmdKrwOQl6yayc'
    b'hgm/e0/HaH86/blvZEvHiz4/p7Awa8K4cUfIrMxkCvUEpNYoAGjpFAhwEwC+JNOrFIg78zi0'
    b'jUx6nCXqawGwwndxOnhH8xdLX/b6efn5xZePH893mR8v+c4sA8BzynjiANDC429SyMTiu85d'
    b'SB6cQtycveMBKAOArxc6xTqS2PD5Yl8KxWKxyqKiohSnkG1vJvO5P0f4/BK3QqvI3ZzFAeBr'
    b'JQBQDgDfSwyABABSnEKDBYB/2CY2kz0PAzUBgLcxrif3youjklNoErnTZv2urVaXlXb6JMtK'
    b'O97zpFlHm7fbnd9a1A/fPp5C/f39rRPHjuWV13XkTqE2AHSSSbM84W8BQEuYO5ABgD/IpIRM'
    b'Ie5VflPqR6D+d6deptMB1P+q1Af3VHoPlgMALZ0CAaZgQB1kFuQyhWoxIL1HMo8cPy7ykXsK'
    b'9VHsI80AgLYbchIpZFnR9EL67gPvFaU4hSwrml6I1IXIXCiSFLoPA+KtD87ps4VfigHpG1u2'
    b'3UgmnS4QfgXqU7uxxT9sE4/JnoeB1jkpNIVO9DzsN2BAvPKaTO4VViPqdzm+7Hk+RP1Ox5dp'
    b'wz0VpxCvO2KueiLuAG4m96O7CQAfhLkDyRTiKJMpxEnQ6/jDBuD3BKRQFgakpVDoIwhgMgC+'
    b'IrOvmZwJrquDPnX8MaKeX+wtZLYL5TvD+zwrlOvfDYDlqQQI3QsRP14DT6EaACRSCZBMoVVi'
    b'QFzHu9OtZNLmfFHPERdmQVMFAG0bPTKAZAq9Te6ZZgD+pHM6nSt83l7nFFrtAQtKofkAeCQS'
    b'AGdqeQZlCr0PgD1k0kCm0DpoN/F6wZ1CnBC88rqR3Ps8jQDY4dTLFGoFQHMq7wA3dod8bnr6'
    b'cDp2TPMz4B9U/Ez4au8EAM2PDOAGMo+D9+AZrlf8sPtIJQB4IZUAUf0nJqhl+A9SKOy2ilk/'
    b'ew/eCvlfUuh+4m0+/zGDuEX2HzPJfOS8xywyGwHeI7oU4t3p2ZTgFja58mIgfv53Q9PoRNqw'
    b'z7HKacP/L5Zpwx82Thv+n5rcz+Gt9U6nXq6wmgDQEBnAYD7+Ap8ol4+u6rsFAAAAAElFTkSu'
    b'QmCC')
index.append('logo_48')
catalog['logo_48'] = logo_48
getlogo_48Data = logo_48.GetData
getlogo_48Image = logo_48.GetImage
getlogo_48Bitmap = logo_48.GetBitmap

#----------------------------------------------------------------------
logo_64 = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAALp0lEQVR42u2bWXAU1xWGT2tG'
    b'HoFxNKxhEaMRIA0KaEeADJLtsO8gQnBsTCpPeU2qUnEMOFBJFXnLWx7ykhezGbPYxEtwjCUs'
    b'ERwQFhIuEAi0zmhDGOOkDJqlJ/9R30Y9A/c21jARVaZLpzQzR13T9+t7z/nPuS1tL+2l7/Oh'
    b'PQXwFMBTACN9DU8BPAXwJAN4g3ZEZb4/0V7tSfcnFQCORbAzCn85rEbhfxFWrfC/BKtS+JfD'
    b'Plb4VwLCyWQCWAX7SOFfA/tA4d8Ae0/hr4QdU/h/Cjus8P8MAA4lE8Ba2PsJDHAT7LjCvwX2'
    b'jmqAsIMK/zYA2J9MAKthHyr862EnFP6NsHcV/p/Ajij8L8NUd/hVADiQTAArYf9Q+O2WgB0g'
    b'uxlitwReBoC3kwkgH9ao8BfAGhT+Ili9wl8Cu6DwL4D9W+FfCAAq/6PpAEB4Hr/GwBziI4YS'
    b'uJfq6h4VGui/kFm0IDUSSg87nA4tOsgrit/dKXqoKz9w5WZdMc1/JkjusJPgN85P0akn6kzp'
    b'KqzX+6L5+aWk625yOp0kzqdIpJdcrgAFg0FyOGbhvRu/U4Wf8L6PQqEAXb16F+9mwsbBUi2X'
    b'fQvWCQDdCQFQzQCNf/4alc+QX2oahiL3awRO0bF4NQPmhjktgHthfPEDYoDuuAH2UWdnF3k8'
    b'PYrLnwIAKn9iABoz5pYVvHnprPRkV9Mi+nmuVCd4yVveSq3/wctfwObARovBs7F+4PhyG/Ya'
    b'GctpjPDxcYa6uk7StGmnFJe/DAA+SSaAlQAgD4KupjUAIA2CWZS1voVavsbLHbB5sGctADi9'
    b'coTvg70OWwh7zgLgJAAcBICRC4IN0/PWFO5qlEd5V9N6AJBGecyASswAvsO7YfPJmAHmwfph'
    b'H4yn8JswMw6Zx4cUCOyjjAxVmkuuDqj3FKwu3nlRrgNcTesA4O8KABsBgGfALlgZGTPAPI4L'
    b'ABwLeIYshv3A4n9fABg5HQAAqwBALoVdTWsBQKoUAWCDALBDADDvMH8nC6T9AsDvBID0OAD7'
    b'AUA1xZMrhS968guKdjbI8/zopiLalivN8x7ylLRT+7dkSOZsWJoFQB0ZhdYdMgSTj2KXSD31'
    b'9NTSlCmfKy7/eQA4q/A/sg5g+hyArDrAf2War2vrrw5H9WhKTsiRmo6cdt8f1p0Bt/Na17e/'
    b'/o2OTDhLJ30ssp71/O7Mgcn+k9f/EiZNy0aOH4scb02DPZSW5ievd0DAic/zvdTb66fJk1kH'
    b'zIKNj/P3wzoAoEsJIEo07HpbfOktqdfnm0BNTTpxwDfWb2yeb27uoZycm9LzMzMnUVvbgDg/'
    b'XgfcpI6ObvxNr+L6fogx9A0bABmR+ZzCr5aiPl8ZAATxajssh2LzfDVdv/4JZWfL+wlTp1Zg'
    b'nXOWeBWWR7E64CzS4MdIg6p+wRIA+DQRAMtg/1T41cWQz7caAO6REeQKaGgN86x4j27cOEyz'
    b'ZsmLoalTNwEA3+HXBeznLF7WAYcS1gE2ABKr9ny+9QIA5/li2Cjh4e88Si0tB2jmTHnDIyNj'
    b'C+SuTAd8BDhvJawDbACsGCQtP9T9AJ9vnQDAed5UenzwDDhCra0HaMYMeT/A49lM7e3J1QE2'
    b'AOx6buqWmM+3VgDY+RAARwUAecfI46kUAN54CIAPBIDEdIANgMTq+ezsYrp2LYRXm8mo6FzC'
    b'w995FjGgFjGgTnp+RsYCLAEWStwYmU2xOuACANTgb/6luL5FAKDyGzoAqa6CDJWVIj7nO9RB'
    b'qaldWih0M5qV9QJxAOI8b1S/On77ye0O0DffRCklxYf36ffzOGpc9kd9Wf7wib/pKHshYjS3'
    b'RilDaVDTAnrrDX94yfYQ+7VweBw+G/Lrerc2ebI/7eJFnkGcQeLzfA91d3ciUJo6YALsGYuf'
    b'dUAbAASGPQO43sdYWIB4yZi+JiCzXjdzbCY92DDpC9693NfbvFKqE4KR1AlnLu3ul/m9OTkT'
    b'KxYu5DTqETfIaXHfghDqgRCS64iEdUBJSQnV1TH1bWSIEZcYXATGdfZnYrZsE3chTfj5s+rg'
    b'3StVvc0rpFI1FEktq720WypVvTNmLK5YvJh1AHd/51KsDvgcafAU0mC1YnwvAYDKbwOgqGgp'
    b'ffEFTyuO4rwGzSnGADi4HBOD3Sku0NTyg1E+eLfpSG/zcmmWCOtp62oad0mrxUyvd+MLFRV8'
    b'B39Lch2gaptvBQCVTrABUFy8ki5c4EH/EfYjGlqDPEAuVd8Wr/9ARoPUGuQOhe5dPdhzbZlU'
    b'6ET0UZWfNe6U6gCv17uloqJiBHVAaekKOneOAbCQybMMkGfAW2S0pBnA78nICKbQ4c8OAsAh'
    b'AJDeYQDYCABSHZCVlbW5vLx8BHVAaenyxwBA2g8AgA0AINUBAFD5CABUOuAVAFDtHNkugUIs'
    b'AY68vAHBkd4aA06TUa9Hhd8MkiaAGgTBWgRBaZ4PRZzzay/tkRZbnuzsshfLylgHsI7IpVgd'
    b'UAcApwGgVjG+CgBQbc7e1wG8CxuvA9opLy9AjY2a+HL2W9NcBw0MdCIX46wU9rvJ0g/AZ53B'
    b'geud3f/dHtFSRsMfHatpQzpAo4FAOJTe2db/55AWDvo0jcZrpDsHky/8ejjc5dT1zkUlJfco'
    b'EpkNjTDB0i9grdFNfn8HlZdzQ4WbJRMpvm1u6AB/IjPAjRnAUKYL+jF5nhoa+qmw8Lb0/Nzc'
    b'cXT5Ms8WzuPxOqGfrl69SbNnf6W4PnW/wRA//Qr/RABQ+W0BFAMAXzTX47wETB3AM+RTAKgB'
    b'ALmUzc2dDwAsZHgTk7s6o2ioH1CLWqAatYCypQVTSVnb5w8A4PTwARg6gKcV53lTB5hC6DCW'
    b'x3EqKJBXiz7fKlEMcVPT7AeYAE6gHH4H5bA0S1Diu8ePVQfwzo25Bg0d0NDwNmaAvB+Qk7Me'
    b'09zsB/BGp7XpeQwA9iv7AfbPB7wCU6W51wBg3/AB2OmA+vrDgJS8foAR/Y8q/Ik/H/AIAHgJ'
    b'7KFYqftdAHC1xkqOZ4Cp5EwA+5X9AHsAW8lQo7IjQR0wb14xnT/PQZCnmpeG0gwDqAKAWgCQ'
    b'B0Gfb75oivKdMoslPvg7zwBAFQCo9u/tgiCX6aog92MAUDVN7+uApXjN29RWHdCCatCPapAT'
    b'M999bks7LP52+vLLDlq6NEpO5xzk6rHI/UP1fCTSjizQQVVVDIvrCE5p1rZ4J7W1tUPuMaA5'
    b'FFvvDz5/AGuD8RLiADyBYvN89+A1EJk6YBI9qANaAaBTCcCmHHYLABk0pAPMKN4vLErB4HQI'
    b'lWdj/LreTy7XLQGLzx8Td/5XEDL9NH26SgeMwwBuUxIPOwBFAMB3jdeaVQfwXa0mzuXGAHmK'
    b'80MO1n4A52fuF/AdZqkcrwN4CZzGElDtO8wHgPMjB6CoaInoB3BT8kEdYORoXfjnxAHg3V0O'
    b'YBwEua//MB1wBGlQ9ZjdWgBQPWSVZAAJ9gPIeIYvER1QCQCqp8SSDGBIB3C5m2cZQFgAMMth'
    b'TnNcDlt3fg4KCGZbvJS+uw7YCACqNPl/A7CHjExgFULWGcB3uJBi+wHWGcCA5sUBOip0wBMM'
    b'wGiKchDkpqeXYnUAbzpykOPzuVjivr/ZLzA2Pw3jIMg6Iodil0gN0mAV0qBq/952fz9hAEIH'
    b'8B6gVQfwAG/Q3LmddOoUf5aPHO9GanOQw2H6W/G+AxoAQwzOxefj8N6a59vwWRvOi8Cfh9fj'
    b'4/ztANBGCxYwIF5e1jzPft7Xb7br6ycMwGZniJsgd6RepzOdwuHh+x0ONwTT14rvdwPAHUri'
    b'kdytMftHXTkwqvJ8KQDUURIPOwBLYKoHEW3/YYHU2+t2j9uPsA5I/tPgdv8QMcI6INHnA4jW'
    b'wRLp+IxwGhz5/wfYBAAqQEkHYPeQFD+/q2pqJvpPVeUAoOr7Jw5A6AC+k7wNbtUB18mot/kz'
    b'zgasE5wWfwsZ9XpU+OPrffa3ir/lOiE+z7eJv+EHKFgHTIrzcz//ml1f/7EA+D4f/wM09k+M'
    b'G+5D1gAAAABJRU5ErkJggg==')
index.append('logo_64')
catalog['logo_64'] = logo_64
getlogo_64Data = logo_64.GetData
getlogo_64Image = logo_64.GetImage
getlogo_64Bitmap = logo_64.GetBitmap

