import mtx


Levels = [{'name':    'Level 1',
           'ground':  mtx.TEXTURE.GROUND.EARTH,
           'wall':    mtx.TEXTURE.WALL.RED_BRICKS,
           'plan':   ['####--',
                      '#t ###',
                      '#  b #',
                      '# #  #',
                      '#  1 #',
                      '######']},

          {'name':    'Level 2',
           'ground':  mtx.TEXTURE.GROUND.EARTH,
           'wall':    mtx.TEXTURE.WALL.RED_BRICKS,
           'plan':   ['-######',
                      '-#1B  #',
                      '### # #',
                      '#  bt #',
                      '# # ###',
                      '#   #--',
                      '#####--']},

          {'name':    'Level 3',
           'ground':  mtx.TEXTURE.GROUND.EARTH,
           'wall':    mtx.TEXTURE.WALL.RED_BRICKS,
           'plan':   ['########',
                      '#t  #tt#',
                      '#tb    #',
                      '#t b#  #',
                      '### # ##',
                      '# b bb #',
                      '#  1   #',
                      '########']},

          {'name':    'Level 4',
           'ground':  mtx.TEXTURE.GROUND.EARTH,
           'wall':    mtx.TEXTURE.WALL.RED_BRICKS,
           'plan':   ['-######-',
                      '-#    ##',
                      '-#b 1b #',
                      '## ### #',
                      '#t     #',
                      '#  # # #',
                      '#tb  #t#',
                      '########']},

          {'name':    'Level 5',
           'ground':  mtx.TEXTURE.GROUND.EARTH,
           'wall':    mtx.TEXTURE.WALL.RED_BRICKS,
           'plan':   ['########',
                      '#     t#',
                      '#  b ###',
                      '####1#--',
                      '-# b #--',
                      '-# # ###',
                      '-#    t#',
                      '-#######']},

          {'name':    'Level 6',
           'ground':  mtx.TEXTURE.GROUND.EARTH,
           'wall':    mtx.TEXTURE.WALL.RED_BRICKS,
           'plan':   ['########',
                      '#t#  #t#',
                      '#   b# #',
                      '# #1b  #',
                      '#  b # #',
                      '# #b   #',
                      '#t#  #t#',
                      '########']},

          {'name':    'Level 7',
           'ground':  mtx.TEXTURE.GROUND.EARTH,
           'wall':    mtx.TEXTURE.WALL.RED_BRICKS,
           'plan':   ['###########',
                      '#   #    t#',
                      '# # # ## ##',
                      '#        #-',
                      '### #### ##',
                      '# b b #t  #',
                      '# #   ### #',
                      '# ###  1# #',
                      '#   ##### #',
                      '###       #',
                      '--#########']},
         ]
